# Basic dependabot.yml file for a Go project using Go modules

version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod" # for Go modules
    directory: "/" # Location of the go.mod file
    schedule:
      interval: "daily" # How often to check for updates

    # Optional: Open pull requests only for the main branch
    target-branch: "master"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
