// Copyright 2026 H0llyW00dzZ
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pakasir/v1/simulation.proto

package pakasirv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PayRequest is the request to simulate a payment in sandbox mode.
type PayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is the unique order identifier.
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// amount is the payment amount in the smallest currency unit.
	Amount        int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_pakasir_v1_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *PayRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PayRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// PayResponse is the response after simulating a payment.
type PayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResponse) Reset() {
	*x = PayResponse{}
	mi := &file_pakasir_v1_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResponse) ProtoMessage() {}

func (x *PayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResponse.ProtoReflect.Descriptor instead.
func (*PayResponse) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_simulation_proto_rawDescGZIP(), []int{1}
}

var File_pakasir_v1_simulation_proto protoreflect.FileDescriptor

const file_pakasir_v1_simulation_proto_rawDesc = "" +
	"\n" +
	"\x1bpakasir/v1/simulation.proto\x12\n" +
	"pakasir.v1\"?\n" +
	"\n" +
	"PayRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\r\n" +
	"\vPayResponse2M\n" +
	"\x11SimulationService\x128\n" +
	"\x03Pay\x12\x16.pakasir.v1.PayRequest\x1a\x17.pakasir.v1.PayResponse\"\x00B\xaf\x01\n" +
	"\x0ecom.pakasir.v1B\x0fSimulationProtoP\x01ZCgithub.com/H0llyW00dzZ/pakasir-go-sdk/src/grpc/pakasir/v1;pakasirv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Pakasir.V1\xca\x02\n" +
	"Pakasir\\V1\xe2\x02\x16Pakasir\\V1\\GPBMetadata\xea\x02\vPakasir::V1b\x06proto3"

var (
	file_pakasir_v1_simulation_proto_rawDescOnce sync.Once
	file_pakasir_v1_simulation_proto_rawDescData []byte
)

func file_pakasir_v1_simulation_proto_rawDescGZIP() []byte {
	file_pakasir_v1_simulation_proto_rawDescOnce.Do(func() {
		file_pakasir_v1_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pakasir_v1_simulation_proto_rawDesc), len(file_pakasir_v1_simulation_proto_rawDesc)))
	})
	return file_pakasir_v1_simulation_proto_rawDescData
}

var file_pakasir_v1_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pakasir_v1_simulation_proto_goTypes = []any{
	(*PayRequest)(nil),  // 0: pakasir.v1.PayRequest
	(*PayResponse)(nil), // 1: pakasir.v1.PayResponse
}
var file_pakasir_v1_simulation_proto_depIdxs = []int32{
	0, // 0: pakasir.v1.SimulationService.Pay:input_type -> pakasir.v1.PayRequest
	1, // 1: pakasir.v1.SimulationService.Pay:output_type -> pakasir.v1.PayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pakasir_v1_simulation_proto_init() }
func file_pakasir_v1_simulation_proto_init() {
	if File_pakasir_v1_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pakasir_v1_simulation_proto_rawDesc), len(file_pakasir_v1_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pakasir_v1_simulation_proto_goTypes,
		DependencyIndexes: file_pakasir_v1_simulation_proto_depIdxs,
		MessageInfos:      file_pakasir_v1_simulation_proto_msgTypes,
	}.Build()
	File_pakasir_v1_simulation_proto = out.File
	file_pakasir_v1_simulation_proto_goTypes = nil
	file_pakasir_v1_simulation_proto_depIdxs = nil
}
