// Copyright 2026 H0llyW00dzZ
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pakasir/v1/transaction.proto

package pakasirv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateRequest is the request to create a new transaction.
type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is the unique order identifier.
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// amount is the payment amount in the smallest currency unit.
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// payment_method is the desired payment method.
	PaymentMethod PaymentMethod `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3,enum=pakasir.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_pakasir_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

// CreateResponse is the response after creating a transaction.
type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payment contains the created payment details.
	Payment       *PaymentInfo `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_pakasir_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

// CancelRequest is the request to cancel an existing transaction.
type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is the unique order identifier.
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// amount is the transaction amount for verification.
	Amount        int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_pakasir_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// CancelResponse is the response after cancelling a transaction.
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_pakasir_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_transaction_proto_rawDescGZIP(), []int{3}
}

// DetailRequest is the request to retrieve transaction details.
type DetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is the unique order identifier.
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// amount is the transaction amount for verification.
	Amount        int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailRequest) Reset() {
	*x = DetailRequest{}
	mi := &file_pakasir_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailRequest) ProtoMessage() {}

func (x *DetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailRequest.ProtoReflect.Descriptor instead.
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *DetailRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DetailRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// DetailResponse is the response containing transaction details.
type DetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transaction contains the transaction details.
	Transaction   *TransactionInfo `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_pakasir_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *DetailResponse) GetTransaction() *TransactionInfo {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_pakasir_v1_transaction_proto protoreflect.FileDescriptor

const file_pakasir_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1cpakasir/v1/transaction.proto\x12\n" +
	"pakasir.v1\x1a\x16pakasir/v1/types.proto\"\x84\x01\n" +
	"\rCreateRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12@\n" +
	"\x0epayment_method\x18\x03 \x01(\x0e2\x19.pakasir.v1.PaymentMethodR\rpaymentMethod\"C\n" +
	"\x0eCreateResponse\x121\n" +
	"\apayment\x18\x01 \x01(\v2\x17.pakasir.v1.PaymentInfoR\apayment\"B\n" +
	"\rCancelRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\x10\n" +
	"\x0eCancelResponse\"B\n" +
	"\rDetailRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"O\n" +
	"\x0eDetailResponse\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.pakasir.v1.TransactionInfoR\vtransaction2\xdd\x01\n" +
	"\x12TransactionService\x12A\n" +
	"\x06Create\x12\x19.pakasir.v1.CreateRequest\x1a\x1a.pakasir.v1.CreateResponse\"\x00\x12A\n" +
	"\x06Cancel\x12\x19.pakasir.v1.CancelRequest\x1a\x1a.pakasir.v1.CancelResponse\"\x00\x12A\n" +
	"\x06Detail\x12\x19.pakasir.v1.DetailRequest\x1a\x1a.pakasir.v1.DetailResponse\"\x00B\xb0\x01\n" +
	"\x0ecom.pakasir.v1B\x10TransactionProtoP\x01ZCgithub.com/H0llyW00dzZ/pakasir-go-sdk/src/grpc/pakasir/v1;pakasirv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Pakasir.V1\xca\x02\n" +
	"Pakasir\\V1\xe2\x02\x16Pakasir\\V1\\GPBMetadata\xea\x02\vPakasir::V1b\x06proto3"

var (
	file_pakasir_v1_transaction_proto_rawDescOnce sync.Once
	file_pakasir_v1_transaction_proto_rawDescData []byte
)

func file_pakasir_v1_transaction_proto_rawDescGZIP() []byte {
	file_pakasir_v1_transaction_proto_rawDescOnce.Do(func() {
		file_pakasir_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pakasir_v1_transaction_proto_rawDesc), len(file_pakasir_v1_transaction_proto_rawDesc)))
	})
	return file_pakasir_v1_transaction_proto_rawDescData
}

var file_pakasir_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pakasir_v1_transaction_proto_goTypes = []any{
	(*CreateRequest)(nil),   // 0: pakasir.v1.CreateRequest
	(*CreateResponse)(nil),  // 1: pakasir.v1.CreateResponse
	(*CancelRequest)(nil),   // 2: pakasir.v1.CancelRequest
	(*CancelResponse)(nil),  // 3: pakasir.v1.CancelResponse
	(*DetailRequest)(nil),   // 4: pakasir.v1.DetailRequest
	(*DetailResponse)(nil),  // 5: pakasir.v1.DetailResponse
	(PaymentMethod)(0),      // 6: pakasir.v1.PaymentMethod
	(*PaymentInfo)(nil),     // 7: pakasir.v1.PaymentInfo
	(*TransactionInfo)(nil), // 8: pakasir.v1.TransactionInfo
}
var file_pakasir_v1_transaction_proto_depIdxs = []int32{
	6, // 0: pakasir.v1.CreateRequest.payment_method:type_name -> pakasir.v1.PaymentMethod
	7, // 1: pakasir.v1.CreateResponse.payment:type_name -> pakasir.v1.PaymentInfo
	8, // 2: pakasir.v1.DetailResponse.transaction:type_name -> pakasir.v1.TransactionInfo
	0, // 3: pakasir.v1.TransactionService.Create:input_type -> pakasir.v1.CreateRequest
	2, // 4: pakasir.v1.TransactionService.Cancel:input_type -> pakasir.v1.CancelRequest
	4, // 5: pakasir.v1.TransactionService.Detail:input_type -> pakasir.v1.DetailRequest
	1, // 6: pakasir.v1.TransactionService.Create:output_type -> pakasir.v1.CreateResponse
	3, // 7: pakasir.v1.TransactionService.Cancel:output_type -> pakasir.v1.CancelResponse
	5, // 8: pakasir.v1.TransactionService.Detail:output_type -> pakasir.v1.DetailResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pakasir_v1_transaction_proto_init() }
func file_pakasir_v1_transaction_proto_init() {
	if File_pakasir_v1_transaction_proto != nil {
		return
	}
	file_pakasir_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pakasir_v1_transaction_proto_rawDesc), len(file_pakasir_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pakasir_v1_transaction_proto_goTypes,
		DependencyIndexes: file_pakasir_v1_transaction_proto_depIdxs,
		MessageInfos:      file_pakasir_v1_transaction_proto_msgTypes,
	}.Build()
	File_pakasir_v1_transaction_proto = out.File
	file_pakasir_v1_transaction_proto_goTypes = nil
	file_pakasir_v1_transaction_proto_depIdxs = nil
}
