// Copyright 2026 H0llyW00dzZ
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pakasir/v1/types.proto

package pakasirv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethod enumerates the supported payment methods.
type PaymentMethod int32

const (
	// PAYMENT_METHOD_UNSPECIFIED is the default zero value.
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	// PAYMENT_METHOD_CIMB_NIAGA_VA is CIMB Niaga Virtual Account.
	PaymentMethod_PAYMENT_METHOD_CIMB_NIAGA_VA PaymentMethod = 1
	// PAYMENT_METHOD_BNI_VA is BNI Virtual Account.
	PaymentMethod_PAYMENT_METHOD_BNI_VA PaymentMethod = 2
	// PAYMENT_METHOD_QRIS is QRIS payment.
	PaymentMethod_PAYMENT_METHOD_QRIS PaymentMethod = 3
	// PAYMENT_METHOD_SAMPOERNA_VA is Sampoerna Virtual Account.
	PaymentMethod_PAYMENT_METHOD_SAMPOERNA_VA PaymentMethod = 4
	// PAYMENT_METHOD_BNC_VA is BNC Virtual Account.
	PaymentMethod_PAYMENT_METHOD_BNC_VA PaymentMethod = 5
	// PAYMENT_METHOD_MAYBANK_VA is Maybank Virtual Account.
	PaymentMethod_PAYMENT_METHOD_MAYBANK_VA PaymentMethod = 6
	// PAYMENT_METHOD_PERMATA_VA is Permata Virtual Account.
	PaymentMethod_PAYMENT_METHOD_PERMATA_VA PaymentMethod = 7
	// PAYMENT_METHOD_ATM_BERSAMA_VA is ATM Bersama Virtual Account.
	PaymentMethod_PAYMENT_METHOD_ATM_BERSAMA_VA PaymentMethod = 8
	// PAYMENT_METHOD_ARTHA_GRAHA_VA is Artha Graha Virtual Account.
	PaymentMethod_PAYMENT_METHOD_ARTHA_GRAHA_VA PaymentMethod = 9
	// PAYMENT_METHOD_BRI_VA is BRI Virtual Account.
	PaymentMethod_PAYMENT_METHOD_BRI_VA PaymentMethod = 10
	// PAYMENT_METHOD_PAYPAL is PayPal payment.
	PaymentMethod_PAYMENT_METHOD_PAYPAL PaymentMethod = 11
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0:  "PAYMENT_METHOD_UNSPECIFIED",
		1:  "PAYMENT_METHOD_CIMB_NIAGA_VA",
		2:  "PAYMENT_METHOD_BNI_VA",
		3:  "PAYMENT_METHOD_QRIS",
		4:  "PAYMENT_METHOD_SAMPOERNA_VA",
		5:  "PAYMENT_METHOD_BNC_VA",
		6:  "PAYMENT_METHOD_MAYBANK_VA",
		7:  "PAYMENT_METHOD_PERMATA_VA",
		8:  "PAYMENT_METHOD_ATM_BERSAMA_VA",
		9:  "PAYMENT_METHOD_ARTHA_GRAHA_VA",
		10: "PAYMENT_METHOD_BRI_VA",
		11: "PAYMENT_METHOD_PAYPAL",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":    0,
		"PAYMENT_METHOD_CIMB_NIAGA_VA":  1,
		"PAYMENT_METHOD_BNI_VA":         2,
		"PAYMENT_METHOD_QRIS":           3,
		"PAYMENT_METHOD_SAMPOERNA_VA":   4,
		"PAYMENT_METHOD_BNC_VA":         5,
		"PAYMENT_METHOD_MAYBANK_VA":     6,
		"PAYMENT_METHOD_PERMATA_VA":     7,
		"PAYMENT_METHOD_ATM_BERSAMA_VA": 8,
		"PAYMENT_METHOD_ARTHA_GRAHA_VA": 9,
		"PAYMENT_METHOD_BRI_VA":         10,
		"PAYMENT_METHOD_PAYPAL":         11,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_pakasir_v1_types_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_pakasir_v1_types_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_pakasir_v1_types_proto_rawDescGZIP(), []int{0}
}

// TransactionStatus enumerates the possible transaction states.
type TransactionStatus int32

const (
	// TRANSACTION_STATUS_UNSPECIFIED is the default zero value.
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	// TRANSACTION_STATUS_PENDING indicates the transaction is awaiting payment.
	TransactionStatus_TRANSACTION_STATUS_PENDING TransactionStatus = 1
	// TRANSACTION_STATUS_COMPLETED indicates the transaction has been paid.
	TransactionStatus_TRANSACTION_STATUS_COMPLETED TransactionStatus = 2
	// TRANSACTION_STATUS_EXPIRED indicates the transaction has expired.
	TransactionStatus_TRANSACTION_STATUS_EXPIRED TransactionStatus = 3
	// TRANSACTION_STATUS_CANCELLED indicates the transaction was cancelled (British spelling).
	TransactionStatus_TRANSACTION_STATUS_CANCELLED TransactionStatus = 4
	// TRANSACTION_STATUS_CANCELED indicates the transaction was canceled (American spelling).
	TransactionStatus_TRANSACTION_STATUS_CANCELED TransactionStatus = 5
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_COMPLETED",
		3: "TRANSACTION_STATUS_EXPIRED",
		4: "TRANSACTION_STATUS_CANCELLED",
		5: "TRANSACTION_STATUS_CANCELED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_COMPLETED":   2,
		"TRANSACTION_STATUS_EXPIRED":     3,
		"TRANSACTION_STATUS_CANCELLED":   4,
		"TRANSACTION_STATUS_CANCELED":    5,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pakasir_v1_types_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_pakasir_v1_types_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pakasir_v1_types_proto_rawDescGZIP(), []int{1}
}

// PaymentInfo contains the details of a created payment.
type PaymentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project is the project slug.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// order_id is the unique order identifier.
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// amount is the original order amount in the smallest currency unit.
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// fee is the payment processing fee.
	Fee int64 `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	// total_payment is amount + fee.
	TotalPayment int64 `protobuf:"varint,5,opt,name=total_payment,json=totalPayment,proto3" json:"total_payment,omitempty"`
	// payment_method is the selected payment method.
	PaymentMethod PaymentMethod `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=pakasir.v1.PaymentMethod" json:"payment_method,omitempty"`
	// payment_number is the virtual account number or payment reference.
	PaymentNumber string `protobuf:"bytes,7,opt,name=payment_number,json=paymentNumber,proto3" json:"payment_number,omitempty"`
	// expired_at is when the payment expires.
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_pakasir_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PaymentInfo) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentInfo) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *PaymentInfo) GetTotalPayment() int64 {
	if x != nil {
		return x.TotalPayment
	}
	return 0
}

func (x *PaymentInfo) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentInfo) GetPaymentNumber() string {
	if x != nil {
		return x.PaymentNumber
	}
	return ""
}

func (x *PaymentInfo) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

// TransactionInfo contains the details of a queried transaction.
type TransactionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// amount is the transaction amount in the smallest currency unit.
	Amount int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// order_id is the unique order identifier.
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// project is the project slug.
	Project string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// status is the current transaction status.
	Status TransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pakasir.v1.TransactionStatus" json:"status,omitempty"`
	// payment_method is the payment method used.
	PaymentMethod PaymentMethod `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=pakasir.v1.PaymentMethod" json:"payment_method,omitempty"`
	// completed_at is when the transaction was completed.
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_pakasir_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pakasir_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_pakasir_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionInfo) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TransactionInfo) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TransactionInfo) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionInfo) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *TransactionInfo) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_pakasir_v1_types_proto protoreflect.FileDescriptor

const file_pakasir_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16pakasir/v1/types.proto\x12\n" +
	"pakasir.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x02\n" +
	"\vPaymentInfo\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x03R\x03fee\x12#\n" +
	"\rtotal_payment\x18\x05 \x01(\x03R\ftotalPayment\x12@\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x19.pakasir.v1.PaymentMethodR\rpaymentMethod\x12%\n" +
	"\x0epayment_number\x18\a \x01(\tR\rpaymentNumber\x129\n" +
	"\n" +
	"expired_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"\x96\x02\n" +
	"\x0fTransactionInfo\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.pakasir.v1.TransactionStatusR\x06status\x12@\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x19.pakasir.v1.PaymentMethodR\rpaymentMethod\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt*\xfb\x02\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYMENT_METHOD_CIMB_NIAGA_VA\x10\x01\x12\x19\n" +
	"\x15PAYMENT_METHOD_BNI_VA\x10\x02\x12\x17\n" +
	"\x13PAYMENT_METHOD_QRIS\x10\x03\x12\x1f\n" +
	"\x1bPAYMENT_METHOD_SAMPOERNA_VA\x10\x04\x12\x19\n" +
	"\x15PAYMENT_METHOD_BNC_VA\x10\x05\x12\x1d\n" +
	"\x19PAYMENT_METHOD_MAYBANK_VA\x10\x06\x12\x1d\n" +
	"\x19PAYMENT_METHOD_PERMATA_VA\x10\a\x12!\n" +
	"\x1dPAYMENT_METHOD_ATM_BERSAMA_VA\x10\b\x12!\n" +
	"\x1dPAYMENT_METHOD_ARTHA_GRAHA_VA\x10\t\x12\x19\n" +
	"\x15PAYMENT_METHOD_BRI_VA\x10\n" +
	"\x12\x19\n" +
	"\x15PAYMENT_METHOD_PAYPAL\x10\v*\xdc\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_COMPLETED\x10\x02\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_EXPIRED\x10\x03\x12 \n" +
	"\x1cTRANSACTION_STATUS_CANCELLED\x10\x04\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_CANCELED\x10\x05B\xaa\x01\n" +
	"\x0ecom.pakasir.v1B\n" +
	"TypesProtoP\x01ZCgithub.com/H0llyW00dzZ/pakasir-go-sdk/src/grpc/pakasir/v1;pakasirv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Pakasir.V1\xca\x02\n" +
	"Pakasir\\V1\xe2\x02\x16Pakasir\\V1\\GPBMetadata\xea\x02\vPakasir::V1b\x06proto3"

var (
	file_pakasir_v1_types_proto_rawDescOnce sync.Once
	file_pakasir_v1_types_proto_rawDescData []byte
)

func file_pakasir_v1_types_proto_rawDescGZIP() []byte {
	file_pakasir_v1_types_proto_rawDescOnce.Do(func() {
		file_pakasir_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pakasir_v1_types_proto_rawDesc), len(file_pakasir_v1_types_proto_rawDesc)))
	})
	return file_pakasir_v1_types_proto_rawDescData
}

var file_pakasir_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pakasir_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pakasir_v1_types_proto_goTypes = []any{
	(PaymentMethod)(0),            // 0: pakasir.v1.PaymentMethod
	(TransactionStatus)(0),        // 1: pakasir.v1.TransactionStatus
	(*PaymentInfo)(nil),           // 2: pakasir.v1.PaymentInfo
	(*TransactionInfo)(nil),       // 3: pakasir.v1.TransactionInfo
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_pakasir_v1_types_proto_depIdxs = []int32{
	0, // 0: pakasir.v1.PaymentInfo.payment_method:type_name -> pakasir.v1.PaymentMethod
	4, // 1: pakasir.v1.PaymentInfo.expired_at:type_name -> google.protobuf.Timestamp
	1, // 2: pakasir.v1.TransactionInfo.status:type_name -> pakasir.v1.TransactionStatus
	0, // 3: pakasir.v1.TransactionInfo.payment_method:type_name -> pakasir.v1.PaymentMethod
	4, // 4: pakasir.v1.TransactionInfo.completed_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pakasir_v1_types_proto_init() }
func file_pakasir_v1_types_proto_init() {
	if File_pakasir_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pakasir_v1_types_proto_rawDesc), len(file_pakasir_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pakasir_v1_types_proto_goTypes,
		DependencyIndexes: file_pakasir_v1_types_proto_depIdxs,
		EnumInfos:         file_pakasir_v1_types_proto_enumTypes,
		MessageInfos:      file_pakasir_v1_types_proto_msgTypes,
	}.Build()
	File_pakasir_v1_types_proto = out.File
	file_pakasir_v1_types_proto_goTypes = nil
	file_pakasir_v1_types_proto_depIdxs = nil
}
